[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ["@api3/airnode-protocol/=lib/airnode/packages/airnode-protocol/"]

solc = "0.8.9"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
